#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Ingo Ruhnke <grumbel@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

"""Regenerates the desktop icons from the game's own 32x32 pixel-art icon.

The game draws the icon (make_app_icon(), also its window icon) and writes it
with --icon; this scales it to the hicolor theme's sizes (whole multiples, so
the pixels stay crisp, and 16 by averaging) and writes a scalable SVG made of
one rectangle per run of equal pixels:

    tools/make_icons.py [--binary build/kurvenrausch] [--out data/icons]
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

APP_ID = "io.github.grumbel.kurvenrausch"
SIZES = [16, 32, 64, 128, 256]

SVG_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
SPDX-FileCopyrightText: 2026 Ingo Ruhnke <grumbel@gmail.com>
SPDX-License-Identifier: GPL-3.0-or-later
Generated by tools/make_icons.py from the game's icon; do not edit.
-->
"""


def svg(icon):
    w, h = icon.size
    rects = []
    for y in range(h):
        x = 0
        while x < w:
            r, g, b, a = icon.getpixel((x, y))
            end = x + 1
            while end < w and icon.getpixel((end, y)) == (r, g, b, a):
                end += 1
            if a:
                rects.append(f'<rect x="{x}" y="{y}" width="{end - x}" height="1" fill="#{r:02x}{g:02x}{b:02x}"/>')
            x = end
    return (SVG_HEADER +
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" '
            'shape-rendering="crispEdges">\n' + "\n".join(rects) + "\n</svg>\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--binary", default="build/kurvenrausch")
    parser.add_argument("--out", default="data/icons")
    args = parser.parse_args()

    binary = Path(args.binary)
    if not binary.exists():
        sys.exit(f"{binary} not found; build the game first")
    out = Path(args.out) / "hicolor"

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "icon.bmp"
        subprocess.run([str(binary), "--icon", str(path)], check=True)
        icon = Image.open(path).convert("RGBA")
        icon.load()

    for size in SIZES:
        if size >= icon.width:
            image = icon.resize((size, size), Image.NEAREST)
        else:
            image = icon.resize((size, size), Image.BOX)
        target = out / f"{size}x{size}" / "apps" / f"{APP_ID}.png"
        target.parent.mkdir(parents=True, exist_ok=True)
        image.save(target, optimize=True)

    target = out / "scalable" / "apps" / f"{APP_ID}.svg"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(svg(icon))
    print(f"wrote {len(SIZES)} PNG sizes and an SVG to {out}")


if __name__ == "__main__":
    main()
